name: Nightly Build and Push

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: bookly
          POSTGRES_PASSWORD: testpass
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:6
        ports:
          - "6379:6379"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Set up Environment Variables
        run: |
          cp .env.example .env

      - name: Run Migrations
        run: alembic upgrade head

      - name: Run Tests
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:testpass@localhost:5432/bookly
          REDIS_URL: redis://localhost:6379
          JWT_SECRET: 1rNfX9r4tYczQIM3PIWzlJMGUQ/2DEC/pTGkeKLtyLk=
          JWT_ALGORITHM: HS256
        run: |
          pytest -v
        

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/saadmalik96/fastapi-beyond-crud:nightly .

      - name: Push Docker Image
        run: docker push ghcr.io/saadmalik96/fastapi-beyond-crud:nightly


  notify-on-failure:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: failure()

    steps:
      - name: Send Failure Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: audrey.kovacek@ethereal.email
          password: vPz8NUCeU5r4GjdpJ5
          subject: "🚨 Nightly Build failed. Push to Dockerhub aborted!"
          body: "The nightly build failed to execute. Please review your workflow for more information."
          to: sparacha@dons.usfca.edu
          from: "GitHub Actions Bot"